import type { NextApiRequest, NextApiResponse } from "next";
import { supabaseServer } from "@/lib/supabaseServer";
import { openai } from "@/lib/openaiClient";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "POST")
    return res.status(405).json({ error: "Only POST allowed" });

  const { id } = req.query;

  try {
    // 1) DB에서 원본 이미지 URL 가져오기 (prompt에 쓰거나, 나중을 위해 남겨둠)
    const { data: monster, error: fetchError } = await supabaseServer
      .from("monsters")
      .select("original_image_url")
      .eq("id", id)
      .single();

    if (fetchError || !monster) {
      console.error(fetchError);
      return res.status(404).json({ error: "Monster not found" });
    }

    const originalUrl = monster.original_image_url;

    // 2) DALL·E 2 이미지 생성 (URL 기반 이미지 변환은 안되지만, 느낌만 비슷하게 생성)
    const response = await openai.images.generate({
      model: "dall-e-2",
      prompt: `
        Generate a cute monster illustration as if it is based on a child's drawing.
        Make it colorful and imaginative, suitable for a children's monster encyclopedia.
        (Note: The original drawing URL is ${originalUrl}, but treat this only as context.)
      `,
      size: "1024x1024",
      // 기본값이 url이라 response_format 안 써도 되지만, 명시적으로 적어도 됨:
      // response_format: "url",
    });

    if (!response.data || !response.data[0] || !response.data[0].url) {
      console.error("OpenAI image response:", response);
      return res.status(500).json({ error: "OpenAI returned no image url" });
    }

    const aiUrl = response.data[0].url;

    // 3) DB에 ai_image_url 업데이트
    const { error: updateError } = await supabaseServer
      .from("monsters")
      .update({ ai_image_url: aiUrl })
      .eq("id", id);

    if (updateError) {
      console.error(updateError);
      return res.status(500).json({ error: updateError.message });
    }

    return res.status(200).json({
      message: "AI monster image generated by DALL·E 2!",
      ai_image_url: aiUrl,
    });

  } catch (err: any) {
    console.error("IMAGE GENERATION ERROR:", err);
    return res.status(500).json({
      error: err.message,
    });
  }
}
